In [1]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

# Installation
Python Numpy Scipy Theano    
Options: h5py Matplotlib Ipython notebook (Jupyter Notebook)  NVIDIA driver, CUDA, cuDNN    
Package Manager: pip Windows: Anaconda, Winpython ... Linux: apt-get/dnf/yum

```
sudo pip install theano
```

# Python
### Shallow Copy vs Deep Copy

In [1]:
a=[1,2,3]
print a
b=a
b[2]=0
print b
print a

[1, 2, 3]
[1, 2, 0]
[1, 2, 0]


### don't write sth like len=1

In [23]:
a=[1,2,3]
print len(a)
print dir(a)
print type(len)

3
['__add__', '__class__', '__contains__', '__delattr__', '__delitem__', '__delslice__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getslice__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__setslice__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']
<type 'builtin_function_or_method'>


### List and Dict

In [6]:
a=[1,2,3]
b={'a':1,'b':2,'c':3}
print type(a), a
print type(b), b

<type 'list'> [1, 2, 3]
<type 'dict'> {'a': 1, 'c': 3, 'b': 2}


### Slice

In [7]:
a=[1,2,3,4,5]
print a[2:]
print a[-2:]

[3, 4, 5]
[4, 5]


# Numpy
### Index

In [8]:
import numpy as np
import numpy.random as RNG
a=np.asarray([1,2,3,4,5,6])
b=np.asarray([0,2,4])
print a[b]

[1 3 5]


### Matrix

In [25]:
a=np.ones((3,2))
b=np.ones((2,3))
print a
print '-------'
print b
print '-------'
print np.dot(a,b)

[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]
-------
[[ 1.  1.  1.]
 [ 1.  1.  1.]]
-------
[[ 2.  2.  2.]
 [ 2.  2.  2.]
 [ 2.  2.  2.]]


### Broadcast

In [12]:
a=np.ones((3,2))
b=np.ones((3,1))
print a+b

[[ 2.  2.]
 [ 2.  2.]
 [ 2.  2.]]


In [24]:
a=np.ones((1,))
b=np.ones((1,1))
c=np.ones((1,1,1))
print a.ndim
print b.ndim
print c.ndim

1
2
3


### axis

In [13]:
a=np.ones((3,2))
print a.sum(axis=0)
print a.sum(axis=1)

[ 3.  3.]
[ 2.  2.  2.]


# Theano
### TensorVariable

In [16]:
import theano
import theano.tensor as T

a=T.matrix()
b=T.vector()
print type(a), type(b)

<class 'theano.tensor.var.TensorVariable'> <class 'theano.tensor.var.TensorVariable'>


### SharedVariable

In [17]:
a=theano.shared(np.ones((3,2)))
print type(a)

<class 'theano.tensor.sharedvar.TensorSharedVariable'>


### Expression

In [18]:
a=T.vector()
b=T.vector()
c=a+b
print type(c)

<class 'theano.tensor.var.TensorVariable'>


### Real example, Linear Regression
$$X=\{x_0, x_1, x_2, ..., x_N\} x_i\in R $$
$$Y=\{y_0, y_1, y_2, ..., y_N\} y_i\in R $$
$$W\in R, b\in R $$
$$\hat y = Wx+b $$
$$Loss = \frac{1}{2}\sum(\hat Y-Y)^2 $$

In [ ]:
#define inputs
x=T.vector()
y=T.vector( )

#define parameters
W=theano.shared(RNG.random())
b=theano.shared(NP.array(0.0))
params = [W,b]

#build an equation 
y_hat = x*W+b

#define a loss
loss = T.mean(0.5*(y_hat-y)**2)

#calculate the gradient 
grads = theano.grad(loss, params)

#gradient descent 
param_update = []
for p,g in zip(params, grads):
    param_update.append((p, p-lr*g))
    
#compile the theano function
train_func = theano.function([x, y], [loss, y_hat], updates=param_update, allow_input_downcast=True)
print 'COMPILE DONE'

### THEANO_FLAGS
```
    THEANO_FLAGS=mode=FAST_RUN,device=gpu,floatX=float32,profile=True
    THEANO_FLAGS=mode=FAST_COMPILE,device=cpu,floatX=float64
```